---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-t-gen-worker, tag: v2.2 }

params:
  NSX_T_VERSION:
  NSX_T_MANAGER_IP:
  NSX_T_MANAGER_ADMIN_USER:
  NSX_T_MANAGER_ROOT_PWD:
  COMPUTE_MANAGER_CONFIGS:
  NSX_T_MANAGER_VM_NAME:
  NSX_T_MANAGER_HOST_NAME:
  NSX_T_CONTROLLERS_CONFIG:
  NSX_T_CONTROLLER_HOST_PREFIX:
  NSX_T_CONTROLLER_VM_NAME_PREFIX:
  NSX_T_CONTROLLER_IPS:
  NSX_T_CONTROLLER_ROOT_PWD:
  NSX_T_CONTROLLER_CLUSTER_PWD:
  NSX_T_EDGE_HOST_PREFIX:
  NSX_T_EDGE_VM_NAME_PREFIX:
  NSX_T_EDGE_IPS:
  NSX_T_EDGE_ROOT_PWD:
  DNSDOMAIN:
  ESXI_HOSTS_ROOT_PWD:

inputs:
  - name: nsx-t-gen-pipeline

run:
  path: nsx-t-gen-pipeline/tasks/uninstall-nsx-t/task.sh
